client/views/home.js

Fix singular/plural peers in home

---

server/views/faq.jade

Tokenly Pockets is a bitcoin and counterparty (counterparty.io) wallet.  For a more detailed explanation of how WebTorrent is integrated into this app, see “p2p Method” in this doc… https://github.com/loon3/Tokenly-Pockets/blob/master/BVAM.md

add Pockets app, fix broken links

---

package.json
server/desktop-api.js
server/web.js

Move all WebTorrent Desktop APIs to their own file
Add comments to server/web.js

Add WebTorrent Desktop telemetry API

---

package.json
secret/index-sample.js
server/auth.js
server/desktop-api.js
server/tracker.js

No graphing yet, just a simple way for us to look at the telemetry logs.

GET /desktop/telemetry with basic auth

---

config.js

WebTorrent Desktop 0.10.0

---

config.js

https://github.com/feross/webtorrent-desktop/releases/tag/v0.11.0

WebTorrent Desktop 0.11.0

---

bin/summarize-telemetry.js
client/style.styl
server/desktop-api.js
server/views/layout.pug
server/views/telemetry-dashboard.pug
server/web.js
static/desktop/telemetry/script.js

Telemetry dashboard

---

.nodemonignore
server/desktop-api.js

Telemetry Dashboard: Fix crash and add "cron job"

---

bin/summarize-telemetry.js
client/style.styl
server/desktop-api.js
server/views/telemetry-dashboard.pug
static/desktop/telemetry/script.js

Telemetry dashboard: add error rate, update every 3h

---

client/style.styl
server/desktop-api.js
server/views/telemetry-dashboard.pug
static/desktop/telemetry/script.js

Telemetry dashboard: errors table

---

bin/summarize-telemetry.js

Telemetry: add usage

---

config.js

WebTorrent Desktop 0.12.0

---

server/desktop-api.js
server/views/telemetry-dashboard.pug
static/desktop/telemetry/script.js

Telemetry dashboard: add version skew

---

static/desktop/telemetry/script.js

They were not in the right place on the x axis. Data from the log file for 2016-08-01, for example, should be graphed at 2016-08-01 23:59:59 -- end of day -- that way it shows up *after* the marker line for a release that happened early in the day on Aug 1 UTC.
@feross

Telemetry dashboard: fix release markers

---

bin/summarize-telemetry.js
server/views/telemetry-dashboard.pug
static/desktop/telemetry/script.js

Telemetry dashboard: add total installs, latest-version error rate

---

server/desktop-api.js

This reverts commit 0d69da204fae7b534a4fafbe000128020dcc9dd0.

End 250K announcement

---

bin/summarize-telemetry.js
static/desktop/telemetry/script.js

Telemetry: add day30to60 retention

---

bin/summarize-telemetry.js

The app doesn't log its version at the time of each uncaught error before 0.13, so for errors with no specified version we guess whether it's `pre-0.12` or `0.12.0`.
@feross

Telemetry: separate app version for each uncaught error

---

config.js

https://github.com/feross/webtorrent-desktop/pull/865

WebTorrent Desktop 0.13.1

---

bin/summarize-telemetry.js

Telemetry: don't misattribute old errors to v0.13+

---

server/views/telemetry-dashboard.pug
static/desktop/telemetry/script.js

Telemetry: fix label placement

---

config.js

WebTorrent Desktop 0.14.0

---

config.js

WebTOrrent Desktop 0.15.0

---

bin/summarize-telemetry.js
server/desktop-api.js

summarize-telemetry: skip bad log lines

---

client/style.styl
client/views/home.js

- First click unmutes video
- All further clicks play/pause the video
Fixes: https://github.com/webtorrent/webtorrent.io/issues/128

Fix Homepage video is blocked by Chrome

---

package.json

fix(package): update semver to version 6.2.0

---

bin/summarize-telemetry.js
client/index.js
client/views/desktop.js
client/views/home.js
server/auth.js
server/desktop-api.js
server/index.js
static/desktop/telemetry/script.js

Use `const` and `let` instead of `var` to conform to the [`no-var`](https://eslint.org/docs/rules/no-var) ESLint rule which is coming in a future version of [JavaScript Standard Style](https://standardjs.com). See https://github.com/standard/eslint-config-standard/pull/152.

Use const and let instead of var

---

package.json

Closes #147
**What is the purpose of this pull request? (put an "X" next to item)**
[ ] Documentation update
[ ] Bug fix
[ ] New feature
[ ] Other, please explain:
**What changes did you make? (Give an overview)**
**Which issue (if any) does this pull request address?**
**Is there anything you'd like reviewers to focus on?**

fix(package): update semver to version 7.3.2

---

package.json

Closes #148
**What is the purpose of this pull request? (put an "X" next to item)**
[ ] Documentation update
[ ] Bug fix
[ ] New feature
[ ] Other, please explain:
**What changes did you make? (Give an overview)**
**Which issue (if any) does this pull request address?**
**Is there anything you'd like reviewers to focus on?**

chore(package): update husky to version 4.2.5

---

server/views/home.pug
server/views/layout.pug

**What is the purpose of this pull request? (put an "X" next to item)**
[x] Documentation update
[ ] Bug fix
[ ] New feature
[ ] Other, please explain:
**What changes did you make? (Give an overview)**
Updated footer links
**Which issue (if any) does this pull request address?**
**Is there anything you'd like reviewers to focus on?**

Add links to GH Discussions, Discord, Wormhole

---

package-lock.json
package.json
server/views/docs.pug
server/views/faq.pug
server/views/free-torrents.pug
server/views/intro.pug

Use latest webtorrent from git for docs using git CLI instead of npm since it seems to remove the docs/ folder.

Support package-lock v2; 
